### ISSUE TITLE
Large volume through compose panel yields broken internet error

### ISSUE THREAD

**Issue by ericbai** [Bolster/bolster-team#59]
Request times out when sending large volume of messages through the compose panel (see Rhody's use case). Fix is to investigate extending the response timeout period. 

## Tasks

- [x] Add stacktrace output for all instances of `log.error`

### Integration 
- [x] PhoneService 

### Unit 
- [x] Contact (getFromNumber)
- [x] SharedContact (getFromNumber)
- [x] PhoneService (storeMessageInTag storing both calls and texts as such
- [x] ContactTag (remove tests for addTextToRecord)

**Comment by ericbai** [comment]
Testing to-dos 

Integration 
- [ ] PhoneService 

Unit 
- [ ] Contact (getFromNumber)
- [ ] SharedContact (getFromNumber)
- [ ] PhoneService (storeMessageInTag storing both calls and texts as such
